name: Build C++ Docker Image, Run Test, Push to ACR  and Deploy to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!README.md'
      - '!docs/**'
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '!README.md'
      - '!docs/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683     #v4.2.2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ libgtest-dev cmake

      - name: Create Build Directory
        run: mkdir build

      - name: Configure CMake
        run: cd build && cmake ..

      - name: Build
        run: cd build && make # This is the crucial step!

      - name: Run tests
        run: ./build/test_project # Use the correct executable name (test_project)

  build:
    runs-on: ubuntu-latest
    needs: [test]
    env:
      ACR_NAME: cplusplus
      IMAGE_NAME: cplusplus
      RESOURCE_GROUP: c-plus-plus-project
      WEBAPP_NAME: cplusplus
      LOCATION: eastus

    permissions:
      id-token: write
      contents: read
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683     #v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2   #v3.10.0

      - name: Azure Login using OIDC
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef51           #v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Extract metadata for Docker
        id: meta
        run: |
          echo "date=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
          echo "tag=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build C++ Docker image
        run: |
          docker build -t ${{ steps.meta.outputs.tag }} .

      - name: Push image to ACR
        run: docker push ${{ steps.meta.outputs.tag }}

      - name: Show pushed image
        run: |
          echo "Image pushed:"
          az acr repository show-tags --name ${{ env.ACR_NAME }} --repository ${{ env.IMAGE_NAME }} --output table

      #### Deployment step to App Service ####
      - name: Deploy image to Azure App Service
        run: |
          echo "Deploying image to Azure App Service..."
          az webapp config container set \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.WEBAPP_NAME }} \
            --docker-custom-image-name ${{ steps.meta.outputs.tag }} \
            --docker-registry-server-url https://${{ env.ACR_NAME }}.azurecr.io

      - name: Azure logout
        run: az logout
        if: always()